### ISSUE TITLE
ejb32.lite.timer.basic.xa fail due to "Unable to determine Dialect without JDBC metadata" error

### ISSUE THREAD

**Issue by starksm64** [jakartaredhat/wildfly-ee11-tck-runner#1]
The runner has been updated to include the derby.yml configuration that sets up the needed jdbc/DBTimer datasource, and there is a new `ejb32.lite.timer.basic.xa.JavaDBSetupExtension` that starts the javadb database. The deployments fail with the following error:

```
2024-08-18 14:19:59,756 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war#ejblite-pu\".__FIRST_PHASE__" => "org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
    Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
    Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)"}}
2024-08-18 14:19:59,756 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war#ejblite-pu\".__FIRST_PHASE__" => "org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
    Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
    Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)"}}
2024-08-18 14:19:59,757 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war#ejblite-pu\".__FIRST_PHASE__" => "org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
    Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
    Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)"}}
2024-08-18 14:19:59,758 DEBUG [org.jboss.weld.deployer] (ServerService Thread Pool -- 82) Weld container cleanup for deployment ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war
2024-08-18 14:19:59,765 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0028: Stopped deployment ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war (runtime-name: ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war) in 7ms
2024-08-18 14:19:59,790 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0272: Suspending server
```

What needs to be done to configure this correctly?

**Comment by scottmarlow** [comment]
I'm not able to recreate this locally yet.  Can you show more of the server.log from before this error occurs?  I think there is a problem referencing the datasource but need to recreate it.

**Comment by starksm64** [comment]
Ok, I could not reproduce it either. See the latest push which is now starting the database, but now I see that there are two persistence.xml files that the build.xml should be pulling in, but they have the same name but different jta-data-source. I'll have to look at the original EE10 deployment in more detail as the deployment method is not correct. These are the two peristence.xml files that the build.xml is referrencing:

ejb30/src/main/java/com/sun/ts/tests/ejb30/lite/tx/cm/common/persistence.xml
ejb32/src/main/java/com/sun/ts/tests/ejb32/lite/timer/basic/xa/persistence.xml

**Comment by scottmarlow** [comment]
I ran the same EE 10 tests and the jakartaeetck/dist/com/sun/ts/tests/ejb32/lite/timer/basic/xa/ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war WEB-INF/classes/META-INF/persistence.xml file contains:

```
<!--

    Copyright (c) 2018, 2021 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence
    https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
             version="3.0">
    <persistence-unit name="ejblite-pu" transaction-type="JTA">
        <jta-data-source>jdbc/DBTimer</jta-data-source>
    </persistence-unit>
</persistence>
```

**Comment by starksm64** [comment]
Right, that is the only one I see in the EE10 archive. The test uses the `com.sun.ts.tests.ejb30.lite.tx.cm.common.CoffeeEJBLite` entity bean, and this is the exception I have now:

``java
2024-08-19 13:56:27,538 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 32) WFLYUT0021: Registered web context: '/ejb32_lite_timer_basic_xa_ejbliteservlet_vehicle_web' for server 'default-server'
2024-08-19 13:56:27,574 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "ejb32_lite_timer_basic_xa_ejbliteservlet_vehicle_web.war" (runtime-name : "ejb32_lite_timer_basic_xa_ejbliteservlet_vehicle_web.war")
2024-08-19 13:56:33,658 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) SQL Error: 20000, SQLState: 42Y07
2024-08-19 13:56:33,658 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) Schema 'CTS1' does not exist
2024-08-19 13:56:33,658 INFO  [org.hibernate.event.internal.DefaultLoadEventListener] (default task-1) HHH000327: Error performing load command: org.hibernate.exception.SQLGrammarException: could not prepare statement [Schema 'CTS1' does not exist] [select ce1_0.ID,ce1_0.BRANDNAME,ce1_0.PRICE from COFFEEEJBLITE ce1_0 where ce1_0.ID=?]
	at org.hibernate@6.4.4.Final//org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:66)
	at org.hibernate@6.4.4.Final//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
	at org.hibernate@6.4.4.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate@6.4.4.Final//org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:194)
	at org.hibernate@6.4.4.Final//org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:187)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)
	at org.hibernate@6.4.4.Final//org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:145)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:117)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.load(SingleIdEntityLoaderStandardImpl.java:75)
	at org.hibernate@6.4.4.Final//org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:3748)
	at org.hibernate@6.4.4.Final//org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3737)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:604)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.loadFromCacheOrDatasource(DefaultLoadEventListener.java:590)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:560)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:544)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:207)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.loadWithRegularProxy(DefaultLoadEventListener.java:290)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:242)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:111)
	at org.hibernate@6.4.4.Final//org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:68)
	at org.hibernate@6.4.4.Final//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
	at org.hibernate@6.4.4.Final//org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1222)
	at org.hibernate@6.4.4.Final//org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1210)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:209)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.internal.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:160)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:149)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:112)
	at org.hibernate@6.4.4.Final//org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:149)
	at org.hibernate@6.4.4.Final//org.hibernate.internal.SessionImpl.find(SessionImpl.java:2424)
	at org.hibernate@6.4.4.Final//org.hibernate.internal.SessionImpl.find(SessionImpl.java:2390)
	at org.jboss.as.jpa@33.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.container.AbstractEntityManager.find(AbstractEntityManager.java:199)
	at deployment.ejb32_lite_timer_basic_xa_ejbliteservlet_vehicle_web.war//com.sun.ts.tests.ejb30.lite.tx.cm.common.CoffeeUtil.findDelete(CoffeeUtil.java:48)
	at deployment.ejb32_lite_timer_basic_xa_ejbliteservlet_vehicle_web.war//com.sun.ts.tests.ejb30.lite.tx.cm.common.CoffeeUtil.findDeletePersist(CoffeeUtil.java:66)
	at deployment.ejb32_lite_timer_basic_xa_ejbliteservlet_vehicle_web.war//com.sun.ts.tests.ejb32.lite.timer.basic.xa.StatelessXATimerBean.persistCoffee(StatelessXATimerBean.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
```

Do you need to run some schema imports before the EE10 tests?

**Comment by scottmarlow** [comment]
> Do you need to run some schema imports before the EE10 tests?

I think Derby might be creating the user/schema account on the fly that we specify in ts.jte but yeah, there are sql DDL/DML scripts run.  In EE 10, ant https://github.com/jakartaee/platform-tck/blob/10.0.x/install/jakartaee/bin/xml/initdb.xml#L493 that ran files in https://github.com/jakartaee/platform-tck/tree/10.0.x/sql when uses did something like:

> cd $TS_HOME/bin
> ant init.${CTS_DB}

**Comment by scottmarlow** [comment]
The Standalone JPA instructions https://github.com/jakartaee/platform-tck/blob/main/jpa-tck/docs/userguide/src/main/jbake/content/config.inc#L93 describes how users can run the (packaged) https://github.com/jakartaee/platform-tck/tree/main/sql scripts.  

We should be able to read/execute the SQL scripts for the platform as well.  Here is some EE 10 TCK output from when that is done with derby:

> configure.basic:
>      [echo] DB URL: jdbc:derby://localhost:1527/derbyDB;create=true
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.sql
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.jstl.sql
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.sprocs.sql
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.persistence.sprocs.sql
>       [sql] 385 of 385 SQL statements executed successfully
> 
> configure.cmp:
>      [echo] DB URL: jdbc:derby://localhost:1527/derbyDB;create=true
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.cmp.sql
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.persistence.sql
>       [sql] Executing resource: jakartaeetck/sql/derby/derby.ddl.interop.sql
>       [sql] 800 of 800 SQL statements executed successfully
>

**Comment by starksm64** [comment]
When I run that script, I see the same error that was being shown in the server.log about the CTS1 schema:

```bash
[starksm@scottryzen bin]$ ant init.derby
Buildfile: /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/build.xml
     [echo] ts.home = /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/xml/../..
     [echo] In a bundle
     [echo] The deliverable currently in use is /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/xml/../../bin.
Trying to override old definition of datatype string

init.derby:
     [echo] ts.home = /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/xml/../..
     [echo] In a bundle
     [echo] The deliverable currently in use is /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/xml/../../bin.

init.derby:
     [echo] ts.home = /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/xml/../..
     [echo] In a bundle
     [echo] The deliverable currently in use is /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/bin/xml/../../bin.

check.configure.cmp:

configure.basic:
     [echo] DB URL: jdbc:derby://localhost:1527/derbyDB;create=true
      [sql] Executing resource: /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck/sql/derby/derby.ddl.sql
      [sql] Failed to execute:  drop table ctstable2 
      [sql] java.sql.SQLSyntaxErrorException: Schema 'CTS1' does not exist
      [sql] Failed to execute:  drop table ctstable1 
      [sql] java.sql.SQLSyntaxErrorException: Schema 'CTS1' does not exist
      [sql] Failed to execute:   drop table concurrencetable 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'CONCURRENCETABLE' because it does not exist.
      [sql] Failed to execute:   drop table Numeric_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'NUMERIC_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Decimal_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'DECIMAL_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Double_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'DOUBLE_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Float_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'FLOAT_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Real_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'REAL_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Bit_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'BIT_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Smallint_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'SMALLINT_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Tinyint_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'TINYINT_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Integer_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'INTEGER_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Bigint_Tab 
      [sql] java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'BIGINT_TAB' because it does not exist.
      [sql] Failed to execute:   drop table Char_Tab 
...
```

**Comment by starksm64** [comment]
Ok, so that was actually a successful run when there was no pre-existing derbyDB. When I went into the derbyDB using ij tool and looked at the schemas and tables, they all existed. When I then run the tests, which are currently just the 
`com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservletTest` test, it succeeds:
```bash
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running ejb32.lite.timer.basic.xa.JavaDBSetupExtension
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservletTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 126.9 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservletTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 127.5 s -- in ejb32.lite.timer.basic.xa.JavaDBSetupExtension
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:09 min
[INFO] Finished at: 2024-08-19T21:29:33-06:00
[INFO] ------------------------------------------------------------------------
```

**Comment by starksm64** [comment]
All passing and I pushed these changes. See if you can reproduce this locally.

```bash
[INFO] --- surefire:3.2.5:test (ejb32) @ wildfly-tck-runner ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running ejb32.lite.timer.basic.xa.JavaDBSetupExtension
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjblitejsfTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 126.6 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjblitejsfTest
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjblitejspTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.9 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjblitejspTest
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservlet2Test
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.4 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservlet2Test
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservletTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.3 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.ClientEjbliteservletTest
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjblitejsfTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.4 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjblitejsfTest
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjblitejspTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.3 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjblitejspTest
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjbliteservlet2Test
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.2 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjbliteservlet2Test
[INFO] Running com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjbliteservletTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.2 s -- in com.sun.ts.tests.ejb32.lite.timer.basic.xa.JsfClientEjbliteservletTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 976.9 s -- in ejb32.lite.timer.basic.xa.JavaDBSetupExtension
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:20 min
[INFO] Finished at: 2024-08-19T21:49:46-06:00
[INFO] ------------------------------------------------------------------------
```
