### ISSUE TITLE
How to specify both <groups>tck-javatest,tck-appclient</groups> without failing on org.jboss.arquillian.container.test.impl.client.deployment.ValidationException: DeploymentScenario contains a target (tck-appclient) not matching any defined Container in the registry.

### ISSUE THREAD

**Issue by scottmarlow** [jakartaredhat/wildfly-ee11-tck-runner#18]
I tried the following in the root pom.xml but that fails:
```
                    <execution>
                        <id>jpa</id>
                        <phase>test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <dependenciesToScan>
                                <dependency>jakarta.tck:persistence-platform-tck-tests</dependency>
                            </dependenciesToScan>
                            <skip>false</skip>
                            <groups>tck-javatest,tck-appclient</groups>
                            <includes>
                                <!-- All tests -->
                                <include>**/*Client*Test*.java</include>
                                <!--include>ee/jakarta/tck/persistence/**/*Test.java</include-->
                                <!-- Examples of single tests -->
                             <!--   <include>ee.jakarta.tck.persistence.core.basic.ClientPmservletTest</include> -->
                             <!--   <include>ee.jakarta.tck.persistence.core.StoredProcedureQuery.Client1PmservletTest</include> -->
                            </includes>
                            <properties>
                                <configurationParameters>
                                    junit.jupiter.extensions.autodetection.enabled = true
                                    junit.platform.output.capture.stderr = true
                                    junit.platform.output.capture.stdout = true
                                    junit.platform.reporting.open.xml.enabled = true
                                    junit.platform.reporting.output.dir = target/junit5-reports
                                </configurationParameters>
                            </properties>
                            <systemPropertyVariables>
                                <arquillian.xml>javatest-arquillian.xml</arquillian.xml>
                                <ts.home>${ts.home}</ts.home>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>

```

Failure message:

> [INFO] Running ee.jakarta.tck.persistence.core.criteriaapi.CriteriaBuilder.Client5AppmanagednotxTest
> [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.019 s <<< FAILURE! -- in ee.jakarta.tck.persistence.core.criteriaapi.CriteriaBuilder.Client5AppmanagednotxTest
> [ERROR] ee.jakarta.tck.persistence.core.criteriaapi.CriteriaBuilder.Client5AppmanagednotxTest -- Time elapsed: 0.019 s <<< ERROR!
> org.jboss.arquillian.container.test.impl.client.deployment.ValidationException: 
> DeploymentScenario contains a target (tck-appclient) not matching any defined Container in the registry.
> Possible causes are: None of the 1 Containers are marked as default or you have defined a @Deployment with a @TargetsContainer of value (tck-appclient) that does not match any found/configured Containers (tck-javatest), see arquillian.xml container@qualifier
>         at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.throwNoMatchFound(DeploymentGenerator.java:307)
>         at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.throwTargetNotFoundValidationException(DeploymentGenerator.java:292)
>         at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.validate(DeploymentGenerator.java:105)
>         at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.generateDeployment(DeploymentGenerator.java:90)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
>         at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:134)
>         at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:106)
>         at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
>         at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:95)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>

**Comment by scottmarlow** [comment]
Other sections that use appclient tests specify:

<arquillian.xml>javatest-appclient-arquillian.xml</arquillian.xml>

And those that don't specify:

<arquillian.xml>javatest-arquillian.xml</arquillian.xml>

I'll try adding separate executions for jpa appclient...

**Comment by scottmarlow** [comment]
Getting further with separate executions:

```
                  <execution>
                        <id>jms-appclient</id>
                        <phase>test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <dependenciesToScan>jakarta.tck:jms</dependenciesToScan>
                            <skip>true</skip>
                            <groups>tck-appclient</groups>
                            <includes>
                                <!-- All tests -->
                                <!--include>com/sun/ts/tests/jms/**/*Test.java</include-->
                                <!-- Examples of single tests -->
                                <!--include>com.sun.ts.tests.jms.core.bytesMsgTopic.BytesMsgTopicTestsJspTest</include-->
                                <include>com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesT2.ClientTest</include>
                            </includes>
                            <properties>
                                <configurationParameters>
                                    junit.jupiter.extensions.autodetection.enabled = true
                                    junit.platform.output.capture.stderr = true
                                    junit.platform.output.capture.stdout = true
                                    junit.platform.reporting.open.xml.enabled = false
                                    junit.platform.reporting.output.dir = target/junit5-reports
                                </configurationParameters>
                            </properties>
                            <systemPropertyVariables>
                                <arquillian.xml>javatest-appclient-arquillian.xml</arquillian.xml>
                                <ts.home>${ts.home}</ts.home>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>

                    <execution>
                        <id>jpa-appclient</id>
                        <phase>test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <dependenciesToScan>
                                <dependency>jakarta.tck:persistence-platform-tck-tests</dependency>
                            </dependenciesToScan>
                            <skip>false</skip>
                            <groups>tck-appclient</groups>
                            <includes>
                                <!-- All tests -->
                                <include>**/*Client*Test*.java</include>
                                <!-- Examples of single tests -->
                            </includes>
                            <properties>
                                <configurationParameters>
                                    junit.jupiter.extensions.autodetection.enabled = true
                                    junit.platform.output.capture.stderr = true
                                    junit.platform.output.capture.stdout = true
                                    junit.platform.reporting.open.xml.enabled = false
                                    junit.platform.reporting.output.dir = target/junit5-reports
                                </configurationParameters>
                            </properties>
                            <systemPropertyVariables>
                                <arquillian.xml>javatest-appclient-arquillian.xml</arquillian.xml>
                                <ts.home>${ts.home}</ts.home>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>


```
