### ISSUE TITLE
ejb3_assembly_metainfandlibdir_ejb3_assembly_metainfandlibdir.ear fails to deploy war

### ISSUE THREAD

**Issue by starksm64** [jakartaredhat/wildfly-ee11-tck-runner#4]
I have updated the deployment archive to match the that seen with EE10 along with the  jboss descriptors, but the war in the ear still fails to deploy as it is not linking to the ejb3_common_helloejbjar_standalone_component_ejb.jar which was successfully deployed.

```log
2024-08-22 00:44:41,902 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.deployment.subunit."ejb3_assembly_metainfandlibdir.ear"."ejb3_assembly_metainfandlibdir_web.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.subunit."ejb3_assembly_metainfandlibdir.ear"."ejb3_assembly_metainfandlibdir_web.war".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of subdeployment "ejb3_assembly_metainfandlibdir_web.war" of deployment "ejb3_assembly_metainfandlibdir.ear"
	at org.jboss.as.server@25.0.0.Beta4//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:173)
	at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
	at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
	at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0406: No Jakarta Enterprise Beans found with interface of type 'com.sun.ts.tests.ejb30.common.helloejbjar.HelloRemoteIF' for binding java:module/env/helloBean2
	at org.jboss.as.ejb3@33.0.0.Beta1-SNAPSHOT//org.jboss.as.ejb3.deployment.processors.EjbInjectionSource.getResourceValue(EjbInjectionSource.java:73)
	at org.jboss.as.ee@33.0.0.Beta1-SNAPSHOT//org.jboss.as.ee.component.deployers.ModuleJndiBindingProcessor.addJndiBinding(ModuleJndiBindingProcessor.java:254)
	at org.jboss.as.ee@33.0.0.Beta1-SNAPSHOT//org.jboss.as.ee.component.deployers.ModuleJndiBindingProcessor.deploy(ModuleJndiBindingProcessor.java:107)
	at org.jboss.as.server@25.0.0.Beta4//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166)
	... 8 more

```

**Comment by scottmarlow** [comment]
I'm guessing the failure I get locally is because of an environment setup issue:

> [INFO] Running com.sun.ts.tests.ejb30.assembly.metainfandlibdir.ClientTest
> [ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 4.757 s <<< FAILURE! -- in com.sun.ts.tests.ejb30.assembly.metainfandlibdir.ClientTest
> [ERROR] com.sun.ts.tests.ejb30.assembly.metainfandlibdir.ClientTest.ejbInjectionInFilterTest -- Time elapsed: 0.030 s <<< ERROR!
> java.lang.Exception: Test case throws exception: java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "java.util.Properties.getProperty(String)" is null
>         at tck.arquillian.protocol.javatest.JavaTestMethodExecutor.invoke(JavaTestMethodExecutor.java:69)
>         at org.jboss.arquillian.container.test.impl.execution.RemoteTestExecuter.execute(RemoteTestExecuter.java:103)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
>         at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:134)
>         at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:106)
>         at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
>         at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:52)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
>         at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
>         at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:118)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
>         at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
>         at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
>         at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
>         at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
>         at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
>         at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:134)
>         at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
>         at org.jboss.arquillian.junit5.ArquillianExtension.interceptInvocation(ArquillianExtension.java:149)
>         at org.jboss.arquillian.junit5.ArquillianExtension.interceptTestMethod(ArquillianExtension.java:89)
>         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>

**Comment by starksm64** [comment]
Yes, I have seen that coming from the test client code when there is a
missing property most likely to an incorrect or incomplete ts.jte file.

**Comment by scottmarlow** [comment]
Fixed my ts.jte setting which was pointing at an uninitiated ts.jte from ee 10.

Is your /home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck folder the EE 11 Platform TCK source?  Or an (extracted) EE 10 Platform TCK binary?

I see ^ referenced in the root pom.xml:  ` <ts.home>/home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck`

**Comment by starksm64** [comment]
/home/starksm/Dev/Jakarta/wildflytck-new/jakartaeetck  is the EE10 tck dist. This was fixed by the update to the JBossXmlProcessor to include the descriptors under WEB-INF instead of META-INF for wars.
